// CBSE Class 12 subjects and chapters
export const CBSE_SUBJECTS = [
  {
    id: 'phy',
    name: 'Physics',
    color: '#2A7AFE',
    icon: '⚡',
    chapters: [
      { name: 'Electric Charges and Fields', weightage: 8 },
      { name: 'Electrostatic Potential and Capacitance', weightage: 7 },
      { name: 'Current Electricity', weightage: 7 },
      { name: 'Moving Charges and Magnetism', weightage: 6 },
      { name: 'Magnetism and Matter', weightage: 4 },
      { name: 'Electromagnetic Induction', weightage: 8 },
      { name: 'Alternating Current', weightage: 7 },
      { name: 'Electromagnetic Waves', weightage: 3 },
      { name: 'Ray Optics and Optical Instruments', weightage: 8 },
      { name: 'Wave Optics', weightage: 5 },
      { name: 'Dual Nature of Radiation and Matter', weightage: 4 },
      { name: 'Atoms', weightage: 4 },
      { name: 'Nuclei', weightage: 4 },
      { name: 'Semiconductor Electronics', weightage: 7 },
      { name: 'Communication Systems', weightage: 3 },
    ],
  },
  {
    id: 'chem',
    name: 'Chemistry',
    color: '#34C759',
    icon: '🧪',
    chapters: [
      { name: 'The Solid State', weightage: 4 },
      { name: 'Solutions', weightage: 5 },
      { name: 'Electrochemistry', weightage: 5 },
      { name: 'Chemical Kinetics', weightage: 5 },
      { name: 'Surface Chemistry', weightage: 4 },
      { name: 'General Principles of Isolation of Elements', weightage: 3 },
      { name: 'The p-Block Elements', weightage: 8 },
      { name: 'The d and f Block Elements', weightage: 5 },
      { name: 'Coordination Compounds', weightage: 5 },
      { name: 'Haloalkanes and Haloarenes', weightage: 4 },
      { name: 'Alcohols, Phenols and Ethers', weightage: 4 },
      { name: 'Aldehydes, Ketones and Carboxylic Acids', weightage: 6 },
      { name: 'Amines', weightage: 4 },
      { name: 'Biomolecules', weightage: 4 },
      { name: 'Polymers', weightage: 3 },
      { name: 'Chemistry in Everyday Life', weightage: 3 },
    ],
  },
  {
    id: 'math',
    name: 'Mathematics',
    color: '#FF9F0A',
    icon: '📐',
    chapters: [
      { name: 'Relations and Functions', weightage: 8 },
      { name: 'Inverse Trigonometric Functions', weightage: 4 },
      { name: 'Matrices', weightage: 5 },
      { name: 'Determinants', weightage: 5 },
      { name: 'Continuity and Differentiability', weightage: 8 },
      { name: 'Application of Derivatives', weightage: 8 },
      { name: 'Integrals', weightage: 8 },
      { name: 'Application of Integrals', weightage: 5 },
      { name: 'Differential Equations', weightage: 5 },
      { name: 'Vector Algebra', weightage: 5 },
      { name: 'Three Dimensional Geometry', weightage: 6 },
      { name: 'Linear Programming', weightage: 5 },
      { name: 'Probability', weightage: 8 },
    ],
  },
  {
    id: 'bio',
    name: 'Biology',
    color: '#FF3B30',
    icon: '🌱',
    chapters: [
      { name: 'Reproduction in Organisms', weightage: 4 },
      { name: 'Sexual Reproduction in Flowering Plants', weightage: 7 },
      { name: 'Human Reproduction', weightage: 7 },
      { name: 'Reproductive Health', weightage: 5 },
      { name: 'Principles of Inheritance and Variation', weightage: 10 },
      { name: 'Molecular Basis of Inheritance', weightage: 8 },
      { name: 'Evolution', weightage: 4 },
      { name: 'Human Health and Disease', weightage: 7 },
      { name: 'Strategies for Enhancement in Food Production', weightage: 4 },
      { name: 'Microbes in Human Welfare', weightage: 4 },
      { name: 'Biotechnology: Principles and Processes', weightage: 7 },
      { name: 'Biotechnology and its Applications', weightage: 5 },
      { name: 'Organisms and Populations', weightage: 4 },
      { name: 'Ecosystem', weightage: 5 },
      { name: 'Biodiversity and Conservation', weightage: 4 },
      { name: 'Environmental Issues', weightage: 3 },
    ],
  },
  {
    id: 'eng',
    name: 'English',
    color: '#675178',
    icon: '📚',
    chapters: [
      { name: 'Flamingo – Prose', weightage: 20 },
      { name: 'Flamingo – Poetry', weightage: 10 },
      { name: 'Vistas – Supplementary Reader', weightage: 10 },
      { name: 'Writing Skills', weightage: 30 },
      { name: 'Grammar', weightage: 30 },
    ],
  },
  {
    id: 'cs',
    name: 'Computer Science',
    color: '#423376',
    icon: '💻',
    chapters: [
      { name: 'Python Revision Tour', weightage: 10 },
      { name: 'Object Oriented Programming', weightage: 15 },
      { name: 'File Handling', weightage: 10 },
      { name: 'Data Structures – Stack', weightage: 8 },
      { name: 'Data Structures – Queue', weightage: 8 },
      { name: 'Database Concepts and MySQL', weightage: 20 },
      { name: 'Computer Networks', weightage: 15 },
      { name: 'Society, Law and Ethics', weightage: 14 },
    ],
  },
]

export const XP_REWARDS = {
  task_completed: 20,
  task_practice: 30,
  task_revise: 15,
  diagnostic_completed: 100,
  mock_test_completed: 200,
  practice_paper_completed: 75,
  streak_7: 150,
  streak_30: 500,
  goal_achieved: 1000,
  flashcard_reviewed: 5,
  note_created: 25,
  doubt_solved: 10,
} as const

export const ACHIEVEMENT_DEFS = [
  { code: 'first_login', title: 'Welcome to Laksh!', desc: 'Completed your first login', icon: '🎉', tier: 'bronze' as const },
  { code: 'goal_set', title: 'Goal Setter', desc: 'Set your first study goal', icon: '🎯', tier: 'bronze' as const },
  { code: 'diagnostic_done', title: 'Know Thyself', desc: 'Completed the diagnostic assessment', icon: '🔍', tier: 'bronze' as const },
  { code: 'streak_7', title: '7-Day Warrior', desc: 'Maintained a 7-day study streak', icon: '🔥', tier: 'silver' as const },
  { code: 'streak_30', title: 'Month Master', desc: 'Maintained a 30-day study streak', icon: '⚡', tier: 'gold' as const },
  { code: 'mock_test_80', title: 'Top Scorer', desc: 'Scored 80%+ in a mock test', icon: '🏆', tier: 'gold' as const },
  { code: 'all_chapters_strength', title: 'Subject Conqueror', desc: 'All chapters at Strength level', icon: '💪', tier: 'platinum' as const },
  { code: 'goal_achieved', title: 'Exam Conqueror', desc: 'Achieved your target score', icon: '👑', tier: 'platinum' as const },
  { code: 'week_challenge', title: 'Challenge Champion', desc: 'Completed a weekly challenge', icon: '🌟', tier: 'silver' as const },
  { code: 'xp_500', title: 'Rising Star', desc: 'Earned 500 XP', icon: '⭐', tier: 'bronze' as const },
  { code: 'xp_5000', title: 'Study Legend', desc: 'Earned 5000 XP', icon: '🌙', tier: 'gold' as const },
  { code: 'flashcard_100', title: 'Memory Master', desc: 'Reviewed 100 flashcards', icon: '🃏', tier: 'silver' as const },
] as const

export const SUBJECT_COLORS: Record<string, string> = {
  phy: '#2A7AFE',
  chem: '#34C759',
  math: '#FF9F0A',
  bio: '#FF3B30',
  eng: '#675178',
  cs: '#423376',
}

export const BOARD = 'CBSE'
export const CLASS = '12'
